sudo: required
services:
  - docker

before_install:
  - docker build -t wesleynewzoo/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true wesleynewzoo/react-test npm test

after_success:
  - docker build -t wesleynewzoo/multi-client ./client
  - docker build -t wesleynewzoo/multi-nginx ./nginx
  - docker build -t wesleynewzoo/multi-server ./server
  - docker build -t wesleynewzoo/multi-worker ./worker
  # log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push to docker hub
  - docker push wesleynewzoo/multi-client
  - docker push wesleynewzoo/multi-nginx
  - docker push wesleynewzoo/multi-server
  - docker push wesleynewzoo/multi-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env-1
  bucket_name: elasticbeanstalk-us-east-2-058305893609
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
